# Test runs
Below follows some test runs of my implementations on basic problems.

### ```SGD``` class on basic first-degree polynomial line-fitting problem

In [402]:
n = 100
np.random.seed(0)
x = np.random.rand(n,1)
y = 4 + 2*x + .05*np.random.rand(n,1)
X = np.c_[np.ones(n), x]

In [403]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print('ols-inversion:\n', beta)

ols-inversion:
 [[4.027904  ]
 [1.99682755]]


In [404]:
from StochasticGradientDescent import SGD

sgd = SGD(epochs=10, batches=5, learning_schedule='optimal', cost_function='ols')
beta = sgd.run(X, y)
print('ols-sgd:\n', beta)

sgd = SGD(epochs=20, batches=10, learning_schedule='optimal', cost_function='ridge')
beta = sgd.run(X, y, lmd=.1)
print('ridge-sgd:\n', beta)

ols-sgd:
 [[3.99789401]
 [1.97782246]]
ridge-sgd:
 [[3.72007746]
 [1.86825833]]


### `SGD` class together with implementations of OLS and Ridge in `ols.py` and `ridge.py` 

In [405]:
import ols, ridge
from utils import *

n = 100
x, y = randmesh(sn=n)
z = 1. + 2.*x + 3.*y + 4.*x*x + 5*x*y + 6*y*y + .03*np.random.rand(n,1)
X = make_design_matrix(x, y, pn=2)

In [406]:
# Direct inversion
beta = np.linalg.inv(X.T @ X) @ X.T @ z
print('ols-inversion:\n', beta)

ols-inversion:
 [[1.02429934]
 [1.98277384]
 [2.97928365]
 [4.00860255]
 [5.01623802]
 [6.00975532]]


In [414]:
# Regular OLS
sgd = SGD(epochs=50, batches=40, learning_schedule='constant', eta0=.5, cost_function='ols')
df = ols.run_ols_kfold(X, z, sgd, k=5, polynomial_orders=[2])
print('ols-sgd:\n', sgd.beta)
df

ols-sgd:
 [[1.07049348]
 [2.10085946]
 [2.90572522]
 [3.96732253]
 [4.93328259]
 [6.12359383]]


pol_order  train_mse  test_mse
2        2.0   0.002434  0.002483

In [409]:
# Ridge
sgd = SGD(epochs=100, batches=40, learning_schedule='invscaling', eta0=.5, cost_function='ridge')
ridge.run_ridge_kfold(X, z, sgd, k=5, polynomial_orders=[2], lambdas=[0.003594])
print('ridge-sgd:\n', sgd.beta)
df = ridge.run_ridge_kfold(X, z, sgd, k=5, polynomial_orders=[2], lambdas=np.logspace(-3,-2,10))
df

ridge-sgd:
 [[8.43104528]
 [0.47606812]
 [0.64298641]
 [1.24295542]
 [1.0490371 ]
 [1.9085351 ]]


lambda  train_mse_2  test_mse_2
0  0.001000     0.003379    0.004296
1  0.001292     0.003106    0.003967
2  0.001668     0.002809    0.003607
3  0.002154     0.002515    0.003240
4  0.002783     0.002271    0.002917
5  0.003594     0.002161    0.002725
6  0.004642     0.002320    0.002807
7  0.005995     0.002960    0.003382
8  0.007743     0.004397    0.004777
9  0.010000     0.007102    0.007470

In [435]:
from FeedForwardNeuralNetwork import Layer
layer = Layer(3, 2)
inputs = np.array([1,2]).reshape((2,1))
layer.feed_forward(inputs)

array([[0.82841798],
       [0.81966086],
       [0.77647364]])

In [453]:
weights = np.random.rand(3,4)
deltas = np.random.rand(4,1)
layer.back_propagate(weights, deltas)
layer.derivatives * (weights @ deltas)

array([[0.13161788],
       [0.06505264],
       [0.1562452 ]])